In [1]:
%load_ext autoreload
%autoreload 2
%load_ext dotenv
%dotenv

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
### Shortcut for package import
from pkgimp import *

from nb2p import database, dataset, config
import nb2p.offline.dataset.kgtorrent as kgtorrent

tqdm.pandas()

In [3]:
DATASET_NAME = "distilkaggle"

In [ ]:
DIRS = config.dirs(DATASET_NAME)
DIRS.makedirs()

making dirs: /ssd/haotian/scs/distilkaggle/processed-unixcoder-ast
making dirs: /ssd/haotian/scs/distilkaggle
making dirs: /ssd/haotian/scs/distilkaggle/processed-unixcoder-full
making dirs: /ssd/haotian/scs/distilkaggle/dfgtree
making dirs: /ssd/haotian/scs/distilkaggle/processed-unixcoder-eda
making dirs: /ssd/haotian/scs/distilkaggle/logs/full
making dirs: /ssd/haotian/scs/distilkaggle/models/full
making dirs: /ssd/haotian/scs/distilkaggle/ipynb

In [5]:
# Connect to database

db, client = database.connect(dataset_name=DATASET_NAME, verbose=True)

Pinged to database nb2p-dk. You successfully connected to MongoDB!

# Preprocess code cells

In [6]:
RAW_DIR = DIRS.base / "raw"

In [ ]:
code_df = pd.read_csv(RAW_DIR / "code.csv")
code_df

In [ ]:
code_df = code_df.rename(columns={"source": "content", "cell_index": "cell_id"})
code_df[:3]

In [ ]:
from nb2p.parser import remove_comments_and_docstrings


def check_and_get_content_no_comment(content: str):
    try:
        return remove_comments_and_docstrings(str(content), "python")
    except Exception as e:
        # print(content)
        print(e)

    return pd.NA


code_df["content_no_comment"] = code_df["content"].progress_apply(
    lambda x: check_and_get_content_no_comment(x)
)
code_df[:3]

In [ ]:
for c in ["kernel_id", "cell_id"]:
    code_df = code_df[~pd.to_numeric(code_df[c], errors="coerce").isnull()]
    code_df[c] = pd.to_numeric(code_df[c], downcast="integer")

code_df

# (Optional) Save result to file to avoid losing processed data (as it's time-consuming)

In [7]:
# # ⚠️WARNING: This cell includes file writing

# code_df.to_csv(DIRS.base / "code_preprocessed.csv", index=False)

In [7]:
code_df = pd.read_csv(DIRS.base / "code_preprocessed.csv")
code_df

,kernel_id,cell_id,content,output_type,execution_count,content_no_comment
0,12034794,3,from mpl_toolkits.mplot3d import Axes3D\nfrom ...,NaN,1.0,from mpl_toolkits.mplot3d import Axes3D\nfrom ...
1,12034794,5,"for dirname, _, filenames in os.walk('/kaggle/...",stream,2.0,"for dirname, _, filenames in os.walk('/kaggle/..."
2,12034794,7,# Distribution graphs (histogram/bar graph) of...,NaN,3.0,"def plotPerColumnDistribution(df, nGraphShown,..."
3,12034794,8,# Correlation matrix\ndef plotCorrelationMatri...,NaN,4.0,"def plotCorrelationMatrix(df, graphWidth):\n ..."
4,12034794,9,# Scatter and density plots\ndef plotScatterMa...,NaN,5.0,"def plotScatterMatrix(df, plotSize, textSize):..."
...,...,...,...,...,...,...
12140204,203109,7,# From plot above we can make desicion how man...,stream,6.0,"plt.figure(figsize=(15, 10))\nplt.hist(df.msg...."
12140205,203109,8,# From plot above we can see that roughly spea...,stream,7.0,"plt.figure(figsize=(15, 10))\nplt.hist(df.msg...."
12140206,203109,9,"# Roughly speaking, the message contains 10 wo...",execute_result,8.0,from wordcloud import WordCloud\ncloud = WordC...
12140207,203109,10,"# At the end, let's show up how are messages d...",display_data,9.0,ds = df['2012-01-01': '2016-12-31']\nds.groupb...
12140208,203109,11,"# From plot above we see, that most 'chatted' ...",NaN,10.0,NaN

# Check Segments

In [8]:
kernel_ids = list(code_df["kernel_id"].unique())

In [9]:
code_df[code_df["kernel_id"] == kernel_ids[20000]]

,kernel_id,cell_id,content,output_type,execution_count,content_no_comment
259599,13157217,2,# This Python 3 environment comes with many he...,stream,1.0,import numpy as np \nimport pandas as pd \nimp...
259600,13157217,3,from sklearn.neighbors import kneighbors_graph...,NaN,2.0,from sklearn.neighbors import kneighbors_graph...
259601,13157217,4,"import warnings\nwarnings.filterwarnings(""igno...",NaN,3.0,"import warnings\nwarnings.filterwarnings(""igno..."
259602,13157217,5,n_sample = 10**5\nlist_distribution_type = ['G...,stream,4.0,n_sample = 10**5\nlist_distribution_type = ['G...
259603,13157217,6,df_stat.to_csv('df_stat.csv')\ndf_stat_short.t...,NaN,5.0,df_stat.to_csv('df_stat.csv')\ndf_stat_short.t...
259604,13157217,7,"fig = plt.figure(figsize = (18, 8 ))\nfig.add_...",display_data,6.0,"fig = plt.figure(figsize = (18, 8 ))\nfig.add_..."
259605,13157217,8,fig.savefig('hubs_positions'),NaN,7.0,fig.savefig('hubs_positions')
259606,13157217,9,NaN,NaN,NaN,NaN

In [10]:
kcid_df = code_df[["kernel_id", "cell_id"]]
kcid_df

          kernel_id  cell_id
0          12034794        3
1          12034794        5
2          12034794        7
3          12034794        8
4          12034794        9
...             ...      ...
12140204     203109        7
12140205     203109        8
12140206     203109        9
12140207     203109       10
12140208     203109       11

[12140209 rows x 2 columns]

In [11]:
def is_prompted(cell_ids: List[int]):
    if len(cell_ids) == 1:
        return False

    result = False
    for i in range(len(cell_ids) - 1):
        if cell_ids[i + 1] - cell_ids[i] > 1:
            result = True

    return result

In [12]:
kernel_id_dfs = {}
for k, v in kcid_df.groupby(["kernel_id"]):
    kernel_id_dfs[k[0]] = v

In [13]:
code_dfs = {}
for k, v in code_df.groupby(["kernel_id"]):
    code_dfs[k[0]] = v

In [14]:
from typing import Tuple
from tqdm.contrib.concurrent import process_map
import tqdm


def para_prompted(d: Tuple[int, pd.DataFrame]):
    kernel_id, df = d
    cell_ids: List[int] = list(df["cell_id"])

    return {"notebook_id": kernel_id, "prompted": is_prompted(cell_ids)}


prompted_result = process_map(
    para_prompted,
    kernel_id_dfs.items(),
    tqdm_class=tqdm.notebook.tqdm,
    chunksize=1000,
    max_workers=os.cpu_count(),
)

  0%|          | 0/510534 [00:00<?, ?it/s]

In [15]:
def para_get_cells_dict(d: Tuple[int, pd.DataFrame]):
    kernel_id, df = d
    df = df.drop(columns=["kernel_id"])

    return {"notebook_id": kernel_id, "cells": df}


cells_dict = process_map(
    para_get_cells_dict,
    code_dfs.items(),
    tqdm_class=tqdm.notebook.tqdm,
    chunksize=1000,
    max_workers=os.cpu_count(),
)

  0%|          | 0/510534 [00:00<?, ?it/s]

In [16]:
prompted_result[:10]

[{'notebook_id': 17375, 'prompted': False},
 {'notebook_id': 17416, 'prompted': False},
 {'notebook_id': 17477, 'prompted': False},
 {'notebook_id': 17485, 'prompted': False},
 {'notebook_id': 17487, 'prompted': False},
 {'notebook_id': 17537, 'prompted': False},
 {'notebook_id': 17548, 'prompted': False},
 {'notebook_id': 17648, 'prompted': False},
 {'notebook_id': 17884, 'prompted': False},
 {'notebook_id': 17896, 'prompted': False}]

In [17]:
def get_segment_ends(cell_ids: List[int]):
    result = []

    for i in range(len(cell_ids) - 1):
        if cell_ids[i + 1] - cell_ids[i] > 1:
            result.append(i)

    return result


# NOTE: the final index will NEVER appear in the result
# This is why we can safely + 1 to get the end range vars
get_segment_ends([1, 2, 4, 5, 8])

[1, 3]

In [18]:
from typing import TypeVar
from itertools import chain

T = TypeVar("T")


def get_segments(cells: List[T], ends: List[int]) -> List[List[T]]:
    end_range_vars = [e + 1 for e in ends]

    pairs = zip(chain([0], end_range_vars), chain(end_range_vars, [None]))
    return [cells[i:j] for i, j in pairs]


get_segments(["1st", "2nd", "3rd", "4th", "5th"], get_segment_ends([1, 2, 4, 5, 8]))

[['1st', '2nd'], ['3rd', '4th'], ['5th']]

In [19]:
from nb2p import fileop

In [20]:
cells_dict[997]

{'notebook_id': 44435,
 'cells':           cell_id                                            content  \
 11610624        2  import numpy as np\nimport matplotlib.pyplot a...
 11610625        4  def plot_history(history):\n    loss_list = [s...
 11610626        6  def plot_confusion_matrix(cm, classes,\n      ...
 11610627        8  iris = datasets.load_iris()\nx = iris.data\ny ...
 11610628       10  x_train, x_test, y_train, y_test = train_test_...
 11610629       12  model = Sequential()\nmodel.add(Dense(8,activa...
 11610630       13                              plot_history(history)
 11610631       15  full_multiclass_report(model,\n               ...
 11610632       17  full_multiclass_report(model,\n               ...
 11610633       19  y = iris.target\n\nx_train, x_test, y_train, y...
 11610634       21  ## First redefine y as categorical variable\ny...
 11610635       23                                                NaN

          output_type  execution_count  \
 11610624         NaN             39.0
 11610625         NaN             40.0
 11610626         NaN             41.0
 11610627         NaN             42.0
 11610628         NaN             44.0
 11610629         NaN             21.0
 11610630         NaN             22.0
 11610631         NaN             32.0
 11610632         NaN             34.0
 11610633         NaN             36.0
 11610634         NaN             38.0
 11610635         NaN              NaN

                                          content_no_comment
 11610624  import numpy as np\nimport matplotlib.pyplot a...
 11610625  def plot_history(history):\n    loss_list = [s...
 11610626  def plot_confusion_matrix(cm, classes,\n      ...
 11610627  iris = datasets.load_iris()\nx = iris.data\ny ...
 11610628  x_train, x_test, y_train, y_test = train_test_...
 11610629  model = Sequential()\nmodel.add(Dense(8,activa...
 11610630                              plot_history(history)
 11610631  full_multiclass_report(model,\n               ...
 11610632  full_multiclass_report(model,\n               ...
 11610633  y = iris.target\nx_train, x_test, y_train, y_t...
 11610634  y = to_categorical(iris.target,3)\nx_train, x_...
 11610635                                                NaN  }

# Save to DB

In [21]:
db.notebook.drop()
db.notebook.create_index(["notebook_id"])

'notebook_id_1'

In [22]:
db.segment.drop()
db.segment.create_index(["notebook_id"])

'notebook_id_1'

In [23]:
db.cell.drop()
db.cell.create_index(["notebook_id"])

'notebook_id_1'

In [24]:
db.notebook.insert_many(prompted_result) is None

False

In [25]:
import pandas as pd
from pymongo.database import Database as PyMongoDB


def get_notebook_object_id(db: PyMongoDB, notebook_id: int):
    result = db.notebook.find_one({"notebook_id": notebook_id})
    if not result:
        raise ValueError(f"cannot find notebook_id: {notebook_id}")

    return result["_id"]


def is_invalid_cell_value(v):
    return (not v) or isinstance(v, float) or (v == np.nan)


def is_valid_list(v):
    return v and isinstance(v, list)


def split_code_lines(v: str):
    if is_invalid_cell_value(v):
        return []
    else:
        return v.split("\n")


def make_cell_record_dicts(d):
    db, client = database.connect(dataset_name=DATASET_NAME)

    nb_id, v = d.values()
    cells_dict = v.to_dict(orient="records")

    nb_obj_id = get_notebook_object_id(db, nb_id)

    test_processed = db.cell.find_one({"notebook_id": nb_obj_id})
    if test_processed:
        return

    with client.start_session() as session:
        with session.start_transaction():
            is_prompted = db.notebook.find_one({"_id": nb_obj_id})["prompted"]

            cells_dict = [
                c for c in cells_dict if not is_invalid_cell_value(c["content"])
            ]

            if not cells_dict:
                print(f"WARN  notebook {nb_id} ({nb_obj_id}) is invalid")
                db.notebook.update_one({"_id": nb_obj_id}, {"$set": {"cells": []}})
                return

            for cell in cells_dict:
                cell["content"] = split_code_lines(cell["content"])
                cell["content_no_comment"] = split_code_lines(
                    cell["content_no_comment"]
                )
                cell["notebook_id"] = nb_obj_id

            result = db.cell.insert_many(cells_dict)
            cell_obj_ids = result.inserted_ids
            db.notebook.update_one(
                {"_id": nb_obj_id}, {"$set": {"cells": cell_obj_ids}}
            )

            if not is_prompted:
                return

            cell_ids = [c["cell_id"] for c in cells_dict]
            segments = get_segments(cell_obj_ids, get_segment_ends(cell_ids))
            # print(len(cells_dict), len(segments), segments)

            segment_obj_ids = []
            for i, s in enumerate(segments):
                result = db.segment.insert_one(
                    {
                        "cells": s,
                        "has_code": True,
                        "notebook_id": nb_obj_id,
                        "segment_id": i,
                    }
                )
                segment_obj_ids.append(result.inserted_id)

            db.notebook.update_one(
                {"_id": nb_obj_id}, {"$set": {"segments": segment_obj_ids}}
            )

In [26]:
# make_cell_record_dicts(cells_dict[997])

In [27]:
process_map(
    make_cell_record_dicts,
    cells_dict,
    chunksize=1000,
    max_workers=os.cpu_count(),
) is None

WARN  notebook 17537 (66f3ce8e975730f2dded4f1a) is invalid

  0%|          | 0/510534 [00:00<?, ?it/s]

WARN  notebook 93491 (66f3ce8e975730f2dded5ec3) is invalid
WARN  notebook 93546 (66f3ce8e975730f2dded5ec8) is invalid
WARN  notebook 144327 (66f3ce8e975730f2dded6e55) is invalid
WARN  notebook 93807 (66f3ce8e975730f2dded5ed6) is invalid
WARN  notebook 21609 (66f3ce8e975730f2dded4f57) is invalid
WARN  notebook 64817 (66f3ce8e975730f2dded5714) is invalid
WARN  notebook 200943 (66f3ce8e975730f2dded7df9) is invalid
WARN  notebook 22996 (66f3ce8e975730f2dded4f77) is invalid
WARN  notebook 145252 (66f3ce8e975730f2dded6e74) is invalid
WARN  notebook 125355 (66f3ce8e975730f2dded6aa1) is invalid
WARN  notebook 23276 (66f3ce8e975730f2dded4f83) is invalid
WARN  notebook 82448 (66f3ce8e975730f2dded5b21) is invalid
WARN  notebook 273451 (66f3ce8e975730f2dded8d98) is invalid
WARN  notebook 258608 (66f3ce8e975730f2dded89bb) is invalid
WARN  notebook 163543 (66f3ce8e975730f2dded727a) is invalid
WARN  notebook 221424 (66f3ce8e975730f2dded81f7) is invalid
WARN  notebook 146194 (66f3ce8e975730f2dded6e9d) is invalid
WARN  notebook 202136 (66f3ce8e975730f2dded7e22) is invalid
WARN  notebook 82794 (66f3ce8e975730f2dded5b3b) is invalid
WARN  notebook 163961 (66f3ce8e975730f2dded728e) is invalid
WARN  notebook 24701 (66f3ce8e975730f2dded4fb1) is invalid
WARN  notebook 325717 (66f3ce8e975730f2dded9571) is invalid
WARN  notebook 325718 (66f3ce8e975730f2dded9572) is invalidWARN  notebook 24798 (66f3ce8e975730f2dded4fb4) is invalid

WARN  notebook 273936 (66f3ce8e975730f2dded8db4) is invalid
WARN  notebook 94753 (66f3ce8e975730f2dded5f30) is invalid
WARN  notebook 127134 (66f3ce8e975730f2dded6acf) is invalid
WARN  notebook 273958 (66f3ce8e975730f2dded8db5) is invalid
WARN  notebook 202322 (66f3ce8e975730f2dded7e30) is invalidWARN  notebook 273963 (66f3ce8e975730f2dded8db6) is invalid

WARN  notebook 24834 (66f3ce8e975730f2dded4fb7) is invalid
WARN  notebook 146649 (66f3ce8e975730f2dded6eb1) is invalid
WARN  notebook 202682 (66f3ce8e975730f2dded7e39) is invalid
WARN  notebook 274131 (66f3ce8e975730f2dded8dc0) is invalid
WARN  notebook 25601 (66f3ce8e975730f2dded4fd2) is invalid
WARN  notebook 164202 (66f3ce8e975730f2dded72ab) is invalid
WARN  notebook 259269 (66f3ce8e975730f2dded89f5) is invalid
WARN  notebook 66786 (66f3ce8e975730f2dded5799) is invalid
WARN  notebook 242073 (66f3ce8e975730f2dded8616) is invalid
WARN  notebook 113914 (66f3ce8e975730f2dded6715) is invalid
WARN  notebook 104523 (66f3ce8e975730f2dded6334) is invalid
WARN  notebook 274513 (66f3ce8e975730f2dded8ddb) is invalid
WARN  notebook 242285 (66f3ce8e975730f2dded861d) is invalid
WARN  notebook 26039 (66f3ce8e975730f2dded4feb) is invalid
WARN  notebook 104639 (66f3ce8e975730f2dded6344) is invalid
WARN  notebook 259722 (66f3ce8e975730f2dded8a0a) is invalidWARN  notebook 242408 (66f3ce8e975730f2dded8627) is invalid

WARN  notebook 26558 (66f3ce8e975730f2dded4ff5) is invalid
WARN  notebook 84871 (66f3ce8e975730f2dded5b8e) is invalid
WARN  notebook 242535 (66f3ce8e975730f2dded862f) is invalid
WARN  notebook 104852 (66f3ce8e975730f2dded6354) is invalid
WARN  notebook 104860 (66f3ce8e975730f2dded6356) is invalid
WARN  notebook 223122 (66f3ce8e975730f2dded8249) is invalid
WARN  notebook 993018 (66f3ce8e975730f2ddeddf9e) is invalid
WARN  notebook 993023 (66f3ce8e975730f2ddeddf9f) is invalid
WARN  notebook 993034 (66f3ce8e975730f2ddeddfa0) is invalid
WARN  notebook 993041 (66f3ce8e975730f2ddeddfa1) is invalid
WARN  notebook 993045 (66f3ce8e975730f2ddeddfa2) is invalid
WARN  notebook 993053 (66f3ce8e975730f2ddeddfa3) is invalid
WARN  notebook 993057 (66f3ce8e975730f2ddeddfa4) is invalid
WARN  notebook 993094 (66f3ce8e975730f2ddeddfa6) is invalid
WARN  notebook 993100 (66f3ce8e975730f2ddeddfa7) is invalid
WARN  notebook 993104 (66f3ce8e975730f2ddeddfa9) is invalidWARN  notebook 129308 (66f3ce8e975730f2dded6b32) is invalid

WARN  notebook 95717 (66f3ce8e975730f2dded5f96) is invalidWARN  notebook 27878 (66f3ce8e975730f2dded5024) is invalid


WARN  notebook 993116 (66f3ce8e975730f2ddeddfaa) is invalidWARN  notebook 95719 (66f3ce8e975730f2dded5f97) is invalid
WARN  notebook 993123 (66f3ce8e975730f2ddeddfab) is invalid
WARN  notebook 993132 (66f3ce8e975730f2ddeddfac) is invalid
WARN  notebook 993133 (66f3ce8e975730f2ddeddfad) is invalid
WARN  notebook 993136 (66f3ce8e975730f2ddeddfae) is invalid
WARN  notebook 993143 (66f3ce8e975730f2ddeddfb0) is invalid
WARN  notebook 993148 (66f3ce8e975730f2ddeddfb1) is invalidWARN  notebook 242958 (66f3ce8e975730f2dded864e) is invalid

WARN  notebook 993152 (66f3ce8e975730f2ddeddfb2) is invalid
WARN  notebook 993159 (66f3ce8e975730f2ddeddfb4) is invalid
WARN  notebook 993163 (66f3ce8e975730f2ddeddfb5) is invalid
WARN  notebook 85696 (66f3ce8e975730f2dded5bc4) is invalid
WARN  notebook 302156 (66f3ce8e975730f2dded9212) is invalid
WARN  notebook 890081 (66f3ce8e975730f2ddedd7ff) is invalid
WARN  notebook 1636320 (66f3ce8e975730f2ddee126b) is invalid
WARN  notebook 243468 (66f3ce8e975730f2dded8666) is invalid
WARN  notebook 115063 (66f3ce8e975730f2dded6772) is invalid
WARN  notebook 105472 (66f3ce8e975730f2dded6398) is invalid
WARN  notebook 149615 (66f3ce8e975730f2dded6f35) is invalid
WARN  notebook 85954 (66f3ce8e975730f2dded5bdc) is invalid
WARN  notebook 68462 (66f3ce8e975730f2dded5809) is invalid
WARN  notebook 105535 (66f3ce8e975730f2dded639f) is invalid
WARN  notebook 149943 (66f3ce8e975730f2dded6f42) is invalid
WARN  notebook 115351 (66f3ce8e975730f2dded6788) is invalid
WARN  notebook 832066 (66f3ce8e975730f2ddedd433) is invalid
WARN  notebook 731463 (66f3ce8e975730f2ddedc4a7) is invalid
WARN  notebook 115383 (66f3ce8e975730f2dded678c) is invalid
WARN  notebook 177956 (66f3ce8e975730f2dded7709) is invalid
WARN  notebook 130840 (66f3ce8e975730f2dded6b79) is invalid
WARN  notebook 29624 (66f3ce8e975730f2dded5071) is invalid
WARN  notebook 224762 (66f3ce8e975730f2dded82a4) is invalid
WARN  notebook 276677 (66f3ce8e975730f2dded8e4d) is invalid
WARN  notebook 131162 (66f3ce8e975730f2dded6b82) is invalid
WARN  notebook 244088 (66f3ce8e975730f2dded868f) is invalid
WARN  notebook 244240 (66f3ce8e975730f2dded8693) is invalid
WARN  notebook 244272 (66f3ce8e975730f2dded8694) is invalid
WARN  notebook 189431 (66f3ce8e975730f2dded7b08) is invalid
WARN  notebook 276812 (66f3ce8e975730f2dded8e5a) is invalid
WARN  notebook 178306 (66f3ce8e975730f2dded7725) is invalid
WARN  notebook 30307 (66f3ce8e975730f2dded5089) is invalid
WARN  notebook 115638 (66f3ce8e975730f2dded67a7) is invalid
WARN  notebook 244340 (66f3ce8e975730f2dded8699) is invalid
WARN  notebook 30360 (66f3ce8e975730f2dded508b) is invalid
WARN  notebook 189456 (66f3ce8e975730f2dded7b0d) is invalid
WARN  notebook 69366 (66f3ce8e975730f2dded583b) is invalid
WARN  notebook 131619 (66f3ce8e975730f2dded6b96) is invalid
WARN  notebook 276948 (66f3ce8e975730f2dded8e63) is invalid
WARN  notebook 166347 (66f3ce8e975730f2dded734b) is invalid
WARN  notebook 1637570 (66f3ce8e975730f2ddee12a6) is invalid
WARN  notebook 30573 (66f3ce8e975730f2dded5096) is invalid
WARN  notebook 206401 (66f3ce8e975730f2dded7ee9) is invalid
WARN  notebook 277100 (66f3ce8e975730f2dded8e6b) is invalid
WARN  notebook 106017 (66f3ce8e975730f2dded63e3) is invalid
WARN  notebook 151248 (66f3ce8e975730f2dded6f7d) is invalid
WARN  notebook 244677 (66f3ce8e975730f2dded86b3) is invalid
WARN  notebook 116023 (66f3ce8e975730f2dded67c5) is invalid
WARN  notebook 96812 (66f3ce8e975730f2dded6011) is invalid
WARN  notebook 244780 (66f3ce8e975730f2dded86bd) is invalid
WARN  notebook 132190 (66f3ce8e975730f2dded6bb6) is invalid
WARN  notebook 70428 (66f3ce8e975730f2dded5866) is invalid
WARN  notebook 226241 (66f3ce8e975730f2dded82dd) is invalid
WARN  notebook 106286 (66f3ce8e975730f2dded63fc) is invalid
WARN  notebook 132348 (66f3ce8e975730f2dded6bbf) is invalid
WARN  notebook 208084 (66f3ce8e975730f2dded7f0d) is invalid
WARN  notebook 1639529 (66f3ce8e975730f2ddee12cc) is invalid
WARN  notebook 116299 (66f3ce8e975730f2dded67dc) is invalid
WARN  notebook 226405 (66f3ce8e975730f2dded82e9) is invalid
WARN  notebook 106458 (66f3ce8e975730f2dded640e) is invalid
WARN  notebook 226557 (66f3ce8e975730f2dded82f2) is invalid
WARN  notebook 226581 (66f3ce8e975730f2dded82f5) is invalid
WARN  notebook 262867 (66f3ce8e975730f2dded8ace) is invalid
WARN  notebook 1793612 (66f3ce8e975730f2ddee2275) is invalid
WARN  notebook 54484 (66f3ce8e975730f2dded54c0) is invalid
WARN  notebook 226900 (66f3ce8e975730f2dded8302) is invalid
WARN  notebook 167355 (66f3ce8e975730f2dded7393) is invalid
WARN  notebook 363076 (66f3ce8e975730f2dded9a53) is invalid
WARN  notebook 71321 (66f3ce8e975730f2dded589a) is invalid
WARN  notebook 32352 (66f3ce8e975730f2dded50f5) is invalid
WARN  notebook 245677 (66f3ce8e975730f2dded8701) is invalid
WARN  notebook 151950 (66f3ce8e975730f2dded6fd5) is invalid
WARN  notebook 209146 (66f3ce8e975730f2dded7f4c) is invalid
WARN  notebook 87486 (66f3ce8e975730f2dded5c81) is invalid
WARN  notebook 87586 (66f3ce8e975730f2dded5c8b) is invalid
WARN  notebook 335189 (66f3ce8e975730f2dded969d) is invalid
WARN  notebook 209408 (66f3ce8e975730f2dded7f5d) is invalid
WARN  notebook 71896 (66f3ce8e975730f2dded58c1) is invalid
WARN  notebook 1073162 (66f3ce8e975730f2ddede45e) is invalid
WARN  notebook 279076 (66f3ce8e975730f2dded8ee0) is invalid
WARN  notebook 279132 (66f3ce8e975730f2dded8ee2) is invalid
WARN  notebook 279133 (66f3ce8e975730f2dded8ee3) is invalid
WARN  notebook 279135 (66f3ce8e975730f2dded8ee4) is invalid
WARN  notebook 191363 (66f3ce8e975730f2dded7b9b) is invalid
WARN  notebook 687842 (66f3ce8e975730f2ddedc160) is invalid
WARN  notebook 1074054 (66f3ce8e975730f2ddede46a) is invalid
WARN  notebook 227856 (66f3ce8e975730f2dded833f) is invalid
WARN  notebook 263990 (66f3ce8e975730f2dded8b1c) is invalid
WARN  notebook 263991 (66f3ce8e975730f2dded8b1d) is invalid
WARN  notebook 335945 (66f3ce8e975730f2dded96b2) is invalid
WARN  notebook 246519 (66f3ce8e975730f2dded8738) is invalid
WARN  notebook 336379 (66f3ce8e975730f2dded96c2) is invalid
WARN  notebook 1484066 (66f3ce8e975730f2ddee03ac) is invalid
WARN  notebook 98311 (66f3ce8e975730f2dded609e) is invalid
WARN  notebook 56577 (66f3ce8e975730f2dded5524) is invalid
WARN  notebook 72804 (66f3ce8e975730f2dded58f5) is invalid
WARN  notebook 1380511 (66f3ce8e975730f2ddedf80c) is invalid
WARN  notebook 1324215 (66f3ce8e975730f2ddedf428) is invalid
WARN  notebook 57028 (66f3ce8e975730f2dded5539) is invalid
WARN  notebook 135283 (66f3ce8e975730f2dded6c5c) is invalid
WARN  notebook 247245 (66f3ce8e975730f2dded8762) is invalid
WARN  notebook 192074 (66f3ce8e975730f2dded7bdf) is invalid
WARN  notebook 280168 (66f3ce8e975730f2dded8f32) is invalid
WARN  notebook 747790 (66f3ce8e975730f2ddedc5a4) is invalid
WARN  notebook 57728 (66f3ce8e975730f2dded5560) is invalid
WARN  notebook 118592 (66f3ce8e975730f2dded689a) is invalid
WARN  notebook 904819 (66f3ce8e975730f2ddedd920) is invalid
WARN  notebook 57886 (66f3ce8e975730f2dded5568) is invalid
WARN  notebook 74449 (66f3ce8e975730f2dded593b) is invalid
WARN  notebook 118863 (66f3ce8e975730f2dded68a9) is invalid
WARN  notebook 1081159 (66f3ce8e975730f2ddede4d1) is invalid
WARN  notebook 88859 (66f3ce8e975730f2dded5d16) is invalid
WARN  notebook 88861 (66f3ce8e975730f2dded5d17) is invalid
WARN  notebook 456364 (66f3ce8e975730f2ddeda69c) is invalid
WARN  notebook 108432 (66f3ce8e975730f2dded64d9) is invalid
WARN  notebook 1012903 (66f3ce8e975730f2ddede0f9) is invalidWARN  notebook 1646315 (66f3ce8e975730f2ddee139b) is invalid

WARN  notebook 58705 (66f3ce8e975730f2dded5587) is invalid
WARN  notebook 230625 (66f3ce8e975730f2dded83bd) is invalidWARN  notebook 169345 (66f3ce8e975730f2dded7443) is invalid

WARN  notebook 169353 (66f3ce8e975730f2dded7444) is invalid
WARN  notebook 36026 (66f3ce8e975730f2dded51b5) is invalid
WARN  notebook 280583 (66f3ce8e975730f2dded8f63) is invalid
WARN  notebook 265926 (66f3ce8e975730f2dded8ba3) is invalid
WARN  notebook 312824 (66f3ce8e975730f2dded935e) is invalid
WARN  notebook 2179051 (66f3ce8e975730f2ddee465f) is invalidWARN  notebook 248941 (66f3ce8e975730f2dded87b5) is invalid

WARN  notebook 907636 (66f3ce8e975730f2ddedd952) is invalid
WARN  notebook 36526 (66f3ce8e975730f2dded51c9) is invalid
WARN  notebook 853969 (66f3ce8e975730f2ddedd56a) is invalid
WARN  notebook 1330325 (66f3ce8e975730f2ddedf48f) is invalid
WARN  notebook 193248 (66f3ce8e975730f2dded7c3f) is invalid
WARN  notebook 99688 (66f3ce8e975730f2dded6130) is invalid
WARN  notebook 99691 (66f3ce8e975730f2dded6131) is invalid
WARN  notebook 231663 (66f3ce8e975730f2dded83e8) is invalid
WARN  notebook 397901 (66f3ce8e975730f2dded9f19) is invalid
WARN  notebook 119804 (66f3ce8e975730f2dded68f5) is invalid
WARN  notebook 181845 (66f3ce8e975730f2dded7869) is invalid
WARN  notebook 266620 (66f3ce8e975730f2dded8bd0) is invalidWARN  notebook 281808 (66f3ce8e975730f2dded8f99) is invalid

WARN  notebook 181915 (66f3ce8e975730f2dded786e) is invalid
WARN  notebook 76589 (66f3ce8e975730f2dded5999) is invalid
WARN  notebook 266695 (66f3ce8e975730f2dded8bd5) is invalid
WARN  notebook 522118 (66f3ce8e975730f2ddedaeb5) is invalid
WARN  notebook 424740 (66f3ce8e975730f2ddeda308) is invalid
WARN  notebook 60463 (66f3ce8e975730f2dded55d7) is invalid
WARN  notebook 100043 (66f3ce8e975730f2dded6155) is invalid
WARN  notebook 1276115 (66f3ce8e975730f2ddedf0d9) is invalid
WARN  notebook 100101 (66f3ce8e975730f2dded615d) is invalid
WARN  notebook 370132 (66f3ce8e975730f2dded9b5a) is invalid
WARN  notebook 858416 (66f3ce8e975730f2ddedd5a8) is invalid
WARN  notebook 100244 (66f3ce8e975730f2dded616d) is invalid
WARN  notebook 157777 (66f3ce8e975730f2dded70e6) is invalid
WARN  notebook 251500 (66f3ce8e975730f2dded8809) is invalid
WARN  notebook 911693 (66f3ce8e975730f2ddedd9a0) is invalid
WARN  notebook 157923 (66f3ce8e975730f2dded70ee) is invalid
WARN  notebook 2183756 (66f3ce8e975730f2ddee46b7) is invalid
WARN  notebook 77371 (66f3ce8e975730f2dded59cc) is invalid
WARN  notebook 1411348 (66f3ce8e975730f2ddedfcb4) is invalid
WARN  notebook 38772 (66f3ce8e975730f2dded522c) is invalid
WARN  notebook 182590 (66f3ce8e975730f2dded78a5) is invalid
WARN  notebook 251839 (66f3ce8e975730f2dded881b) is invalid
WARN  notebook 170892 (66f3ce8e975730f2dded74bc) is invalid
WARN  notebook 100521 (66f3ce8e975730f2dded618a) is invalid
WARN  notebook 400269 (66f3ce8e975730f2dded9f61) is invalid
WARN  notebook 525426 (66f3ce8e975730f2ddedaef4) is invalid
WARN  notebook 485934 (66f3ce8e975730f2ddedab26) is invalid
WARN  notebook 77780 (66f3ce8e975730f2dded59e5) is invalid
WARN  notebook 90623 (66f3ce8e975730f2dded5db1) is invalid
WARN  notebook 138860 (66f3ce8e975730f2dded6d3d) is invalid
WARN  notebook 525792 (66f3ce8e975730f2ddedaf06) is invalid
WARN  notebook 78115 (66f3ce8e975730f2dded59ff) is invalid
WARN  notebook 159024 (66f3ce8e975730f2dded7128) is invalid
WARN  notebook 171339 (66f3ce8e975730f2dded74e6) is invalid
WARN  notebook 267933 (66f3ce8e975730f2dded8c35) is invalid
WARN  notebook 487298 (66f3ce8e975730f2ddedab4c) is invalid
WARN  notebook 1987523 (66f3ce8e975730f2ddee3756) is invalid
WARN  notebook 268067 (66f3ce8e975730f2dded8c3e) is invalid
WARN  notebook 761683 (66f3ce8e975730f2ddedc674) is invalid
WARN  notebook 110340 (66f3ce8e975730f2dded6590) is invalid
WARN  notebook 62219 (66f3ce8e975730f2dded564b) is invalid
WARN  notebook 101080 (66f3ce8e975730f2dded61c6) is invalid
WARN  notebook 78396 (66f3ce8e975730f2dded5a17) is invalid
WARN  notebook 234043 (66f3ce8e975730f2dded8473) is invalid
WARN  notebook 402333 (66f3ce8e975730f2dded9fa3) is invalid
WARN  notebook 253063 (66f3ce8e975730f2dded8868) is invalid
WARN  notebook 101241 (66f3ce8e975730f2dded61da) is invalid
WARN  notebook 286819 (66f3ce8e975730f2dded902b) is invalid
WARN  notebook 488186 (66f3ce8e975730f2ddedab73) is invalid
WARN  notebook 172008 (66f3ce8e975730f2dded7513) is invalid
WARN  notebook 1491865 (66f3ce8e975730f2ddee04d4) is invalid
WARN  notebook 91543 (66f3ce8e975730f2dded5dff) is invalid
WARN  notebook 101406 (66f3ce8e975730f2dded61e6) is invalid
WARN  notebook 78766 (66f3ce8e975730f2dded5a38) is invalid
WARN  notebook 91599 (66f3ce8e975730f2dded5e04) is invalid
WARN  notebook 287359 (66f3ce8e975730f2dded9039) is invalid
WARN  notebook 110883 (66f3ce8e975730f2dded65b9) is invalid
WARN  notebook 268443 (66f3ce8e975730f2dded8c68) is invalidWARN  notebook 287704 (66f3ce8e975730f2dded903d) is invalid

WARN  notebook 78889 (66f3ce8e975730f2dded5a44) is invalid
WARN  notebook 101474 (66f3ce8e975730f2dded61f5) is invalid
WARN  notebook 195512 (66f3ce8e975730f2dded7d02) is invalid
WARN  notebook 640045 (66f3ce8e975730f2ddedb72b) is invalid
WARN  notebook 183814 (66f3ce8e975730f2dded7918) is invalid
WARN  notebook 141142 (66f3ce8e975730f2dded6da6) is invalid
WARN  notebook 79292 (66f3ce8e975730f2dded5a59) is invalid
WARN  notebook 253952 (66f3ce8e975730f2dded889a) is invalid
WARN  notebook 268865 (66f3ce8e975730f2dded8c88) is invalid
WARN  notebook 1838078 (66f3ce8e975730f2ddee2809) is invalid
WARN  notebook 195891 (66f3ce8e975730f2dded7d1c) is invalid
WARN  notebook 79528 (66f3ce8e975730f2dded5a6d) is invalidWARN  notebook 101866 (66f3ce8e975730f2dded621b) is invalid

WARN  notebook 111263 (66f3ce8e975730f2dded65e8) is invalid
WARN  notebook 43299 (66f3ce8e975730f2dded52cb) is invalid
WARN  notebook 464810 (66f3ce8e975730f2ddeda7a0) is invalid
WARN  notebook 269099 (66f3ce8e975730f2dded8c95) is invalid
WARN  notebook 160417 (66f3ce8e975730f2dded718e) is invalid
WARN  notebook 196168 (66f3ce8e975730f2dded7d2e) is invalid
WARN  notebook 141684 (66f3ce8e975730f2dded6dcc) is invalid
WARN  notebook 793621 (66f3ce8e975730f2ddedce72) is invalid
WARN  notebook 79819 (66f3ce8e975730f2dded5a7e) is invalid
WARN  notebook 122616 (66f3ce8e975730f2dded69e4) is invalid
WARN  notebook 216924 (66f3ce8e975730f2dded8105) is invalid
WARN  notebook 1034081 (66f3ce8e975730f2ddede214) is invalid
WARN  notebook 2094213 (66f3ce8e975730f2ddee3f9b) is invalid
WARN  notebook 235953 (66f3ce8e975730f2dded84d7) is invalid
WARN  notebook 290022 (66f3ce8e975730f2dded9085) is invalid
WARN  notebook 235979 (66f3ce8e975730f2dded84d9) is invalid
WARN  notebook 235986 (66f3ce8e975730f2dded84da) is invalid
WARN  notebook 217128 (66f3ce8e975730f2dded8110) is invalid
WARN  notebook 92639 (66f3ce8e975730f2dded5e65) is invalid
WARN  notebook 184752 (66f3ce8e975730f2dded7967) is invalid
WARN  notebook 348121 (66f3ce8e975730f2dded985a) is invalid
WARN  notebook 1420988 (66f3ce8e975730f2ddedfd77) is invalid
WARN  notebook 405815 (66f3ce8e975730f2ddeda026) is invalid
WARN  notebook 432855 (66f3ce8e975730f2ddeda406) is invalid
WARN  notebook 255450 (66f3ce8e975730f2dded88e8) is invalid
WARN  notebook 123196 (66f3ce8e975730f2dded6a14) is invalid
WARN  notebook 217618 (66f3ce8e975730f2dded812d) is invalid
WARN  notebook 217657 (66f3ce8e975730f2dded8130) is invalid
WARN  notebook 255587 (66f3ce8e975730f2dded88f3) is invalid
WARN  notebook 236731 (66f3ce8e975730f2dded8502) is invalid
WARN  notebook 376012 (66f3ce8e975730f2dded9c49) is invalid
WARN  notebook 236838 (66f3ce8e975730f2dded8508) is invalid
WARN  notebook 236847 (66f3ce8e975730f2dded8509) is invalid
WARN  notebook 236922 (66f3ce8e975730f2dded850b) is invalid
WARN  notebook 255721 (66f3ce8e975730f2dded88fe) is invalid
WARN  notebook 92951 (66f3ce8e975730f2dded5e8f) is invalid
WARN  notebook 1811380 (66f3ce8e975730f2ddee2482) is invalid
WARN  notebook 123634 (66f3ce8e975730f2dded6a35) is invalid
WARN  notebook 185164 (66f3ce8e975730f2dded7993) is invalid
WARN  notebook 197375 (66f3ce8e975730f2dded7d83) is invalid
WARN  notebook 814718 (66f3ce8e975730f2ddedd2af) is invalid
WARN  notebook 320833 (66f3ce8e975730f2dded94b4) is invalid
WARN  notebook 161532 (66f3ce8e975730f2dded71ef) is invalid
WARN  notebook 123873 (66f3ce8e975730f2dded6a42) is invalid
WARN  notebook 1998010 (66f3ce8e975730f2ddee3818) is invalid
WARN  notebook 255979 (66f3ce8e975730f2dded8918) is invalid
WARN  notebook 1041487 (66f3ce8e975730f2ddede26e) is invalid

False

In [28]:
for nb in db.notebook.find():
    if len(nb["cells"]) == 0:
        print(nb["_id"])

        db.notebook.update_one({"_id": nb["_id"]}, {"$set": {"can_parse": False}})
    else:
        db.notebook.update_one({"_id": nb["_id"]}, {"$set": {"can_parse": True}})

66f3ce8e975730f2dded4f1a
66f3ce8e975730f2dded4f57
66f3ce8e975730f2dded4f77
66f3ce8e975730f2dded4f83
66f3ce8e975730f2dded4fb1
66f3ce8e975730f2dded4fb4
66f3ce8e975730f2dded4fb7
66f3ce8e975730f2dded4fd2
66f3ce8e975730f2dded4feb
66f3ce8e975730f2dded4ff5
66f3ce8e975730f2dded5024
66f3ce8e975730f2dded5071
66f3ce8e975730f2dded5089
66f3ce8e975730f2dded508b
66f3ce8e975730f2dded5096
66f3ce8e975730f2dded50f5
66f3ce8e975730f2dded51b5
66f3ce8e975730f2dded51c9
66f3ce8e975730f2dded522c
66f3ce8e975730f2dded52cb
66f3ce8e975730f2dded54c0
66f3ce8e975730f2dded5524
66f3ce8e975730f2dded5539
66f3ce8e975730f2dded5560
66f3ce8e975730f2dded5568
66f3ce8e975730f2dded5587
66f3ce8e975730f2dded55d7
66f3ce8e975730f2dded564b
66f3ce8e975730f2dded5714
66f3ce8e975730f2dded5799
66f3ce8e975730f2dded5809
66f3ce8e975730f2dded583b
66f3ce8e975730f2dded5866
66f3ce8e975730f2dded589a
66f3ce8e975730f2dded58c1
66f3ce8e975730f2dded58f5
66f3ce8e975730f2dded593b
66f3ce8e975730f2dded5999
66f3ce8e975730f2dded59cc
66f3ce8e975730f2dded59e5
66f3ce8e975730f2dded59ff
66f3ce8e975730f2dded5a17
66f3ce8e975730f2dded5a38
66f3ce8e975730f2dded5a44
66f3ce8e975730f2dded5a59
66f3ce8e975730f2dded5a6d
66f3ce8e975730f2dded5a7e
66f3ce8e975730f2dded5b21
66f3ce8e975730f2dded5b3b
66f3ce8e975730f2dded5b8e
66f3ce8e975730f2dded5bc4
66f3ce8e975730f2dded5bdc
66f3ce8e975730f2dded5c81
66f3ce8e975730f2dded5c8b
66f3ce8e975730f2dded5d16
66f3ce8e975730f2dded5d17
66f3ce8e975730f2dded5db1
66f3ce8e975730f2dded5dff
66f3ce8e975730f2dded5e04
66f3ce8e975730f2dded5e65
66f3ce8e975730f2dded5e8f
66f3ce8e975730f2dded5ec3
66f3ce8e975730f2dded5ec8
66f3ce8e975730f2dded5ed6
66f3ce8e975730f2dded5f30
66f3ce8e975730f2dded5f96
66f3ce8e975730f2dded5f97
66f3ce8e975730f2dded6011
66f3ce8e975730f2dded609e
66f3ce8e975730f2dded6130
66f3ce8e975730f2dded6131
66f3ce8e975730f2dded6155
66f3ce8e975730f2dded615d
66f3ce8e975730f2dded616d
66f3ce8e975730f2dded618a
66f3ce8e975730f2dded61c6
66f3ce8e975730f2dded61da
66f3ce8e975730f2dded61e6
66f3ce8e975730f2dded61f5
66f3ce8e975730f2dded621b
66f3ce8e975730f2dded6334
66f3ce8e975730f2dded6344
66f3ce8e975730f2dded6354
66f3ce8e975730f2dded6356
66f3ce8e975730f2dded6398
66f3ce8e975730f2dded639f
66f3ce8e975730f2dded63e3
66f3ce8e975730f2dded63fc
66f3ce8e975730f2dded640e
66f3ce8e975730f2dded64d9
66f3ce8e975730f2dded6590
66f3ce8e975730f2dded65b9
66f3ce8e975730f2dded65e8
66f3ce8e975730f2dded6661
66f3ce8e975730f2dded6715
66f3ce8e975730f2dded6772
66f3ce8e975730f2dded6788
66f3ce8e975730f2dded678c
66f3ce8e975730f2dded67a7
66f3ce8e975730f2dded67c5
66f3ce8e975730f2dded67dc
66f3ce8e975730f2dded689a
66f3ce8e975730f2dded68a9
66f3ce8e975730f2dded68f5
66f3ce8e975730f2dded69e4
66f3ce8e975730f2dded6a14
66f3ce8e975730f2dded6a35
66f3ce8e975730f2dded6a42
66f3ce8e975730f2dded6aa1
66f3ce8e975730f2dded6acf
66f3ce8e975730f2dded6b32
66f3ce8e975730f2dded6b79
66f3ce8e975730f2dded6b82
66f3ce8e975730f2dded6b96
66f3ce8e975730f2dded6bb6
66f3ce8e975730f2dded6bbf
66f3ce8e975730f2dded6c5c
66f3ce8e975730f2dded6d3d
66f3ce8e975730f2dded6da6
66f3ce8e975730f2dded6dcc
66f3ce8e975730f2dded6e3f
66f3ce8e975730f2dded6e55
66f3ce8e975730f2dded6e74
66f3ce8e975730f2dded6e9d
66f3ce8e975730f2dded6eb1
66f3ce8e975730f2dded6f35
66f3ce8e975730f2dded6f42
66f3ce8e975730f2dded6f7d
66f3ce8e975730f2dded6fd5
66f3ce8e975730f2dded70e6
66f3ce8e975730f2dded70ee
66f3ce8e975730f2dded7128
66f3ce8e975730f2dded718e
66f3ce8e975730f2dded71ef
66f3ce8e975730f2dded727a
66f3ce8e975730f2dded728e
66f3ce8e975730f2dded72ab
66f3ce8e975730f2dded734b
66f3ce8e975730f2dded7393
66f3ce8e975730f2dded7443
66f3ce8e975730f2dded7444
66f3ce8e975730f2dded74bc
66f3ce8e975730f2dded74e6
66f3ce8e975730f2dded7513
66f3ce8e975730f2dded7709
66f3ce8e975730f2dded7725
66f3ce8e975730f2dded7869
66f3ce8e975730f2dded786e
66f3ce8e975730f2dded78a5
66f3ce8e975730f2dded7918
66f3ce8e975730f2dded7967
66f3ce8e975730f2dded7993
66f3ce8e975730f2dded79ae
66f3ce8e975730f2dded7b08
66f3ce8e975730f2dded7b0d
66f3ce8e975730f2dded7b9b
66f3ce8e975730f2dded7bdf
66f3ce8e975730f2dded7c3f
66f3ce8e975730f2dded7d02
66f3ce8e975730f2dded7d1c
66f3ce8e975730f2dded7d2e
66f3ce8e975730f2dded7d83
66f3ce8e975730f2dded7df9
66f3ce8e975730f2dded7e22
66f3ce8e975730f2dded7e30
66f3ce8e975730f2dded7e39
66f3ce8e975730f2dded7ee9
66f3ce8e975730f2dded7f0d
66f3ce8e975730f2dded7f4c
66f3ce8e975730f2dded7f5d
66f3ce8e975730f2dded8105
66f3ce8e975730f2dded8110
66f3ce8e975730f2dded812d
66f3ce8e975730f2dded8130
66f3ce8e975730f2dded817d
66f3ce8e975730f2dded81f7
66f3ce8e975730f2dded8249
66f3ce8e975730f2dded82a4
66f3ce8e975730f2dded82dd
66f3ce8e975730f2dded82e9
66f3ce8e975730f2dded82f2
66f3ce8e975730f2dded82f5
66f3ce8e975730f2dded8302
66f3ce8e975730f2dded833f
66f3ce8e975730f2dded83bd
66f3ce8e975730f2dded83e8
66f3ce8e975730f2dded8473
66f3ce8e975730f2dded84d7
66f3ce8e975730f2dded84d9
66f3ce8e975730f2dded84da
66f3ce8e975730f2dded8502
66f3ce8e975730f2dded8508
66f3ce8e975730f2dded8509
66f3ce8e975730f2dded850b
66f3ce8e975730f2dded8558
66f3ce8e975730f2dded8595
66f3ce8e975730f2dded85bd
66f3ce8e975730f2dded8616
66f3ce8e975730f2dded861d
66f3ce8e975730f2dded8627
66f3ce8e975730f2dded862f
66f3ce8e975730f2dded864e
66f3ce8e975730f2dded8666
66f3ce8e975730f2dded868f
66f3ce8e975730f2dded8693
66f3ce8e975730f2dded8694
66f3ce8e975730f2dded8699
66f3ce8e975730f2dded86b3
66f3ce8e975730f2dded86bd
66f3ce8e975730f2dded8701
66f3ce8e975730f2dded8738
66f3ce8e975730f2dded8762
66f3ce8e975730f2dded87b5
66f3ce8e975730f2dded8809
66f3ce8e975730f2dded881b
66f3ce8e975730f2dded8868
66f3ce8e975730f2dded889a
66f3ce8e975730f2dded88e8
66f3ce8e975730f2dded88f3
66f3ce8e975730f2dded88fe
66f3ce8e975730f2dded8918
66f3ce8e975730f2dded8934
66f3ce8e975730f2dded8967
66f3ce8e975730f2dded896a
66f3ce8e975730f2dded8976
66f3ce8e975730f2dded89bb
66f3ce8e975730f2dded89f5
66f3ce8e975730f2dded8a0a
66f3ce8e975730f2dded8ace
66f3ce8e975730f2dded8b1c
66f3ce8e975730f2dded8b1d
66f3ce8e975730f2dded8ba3
66f3ce8e975730f2dded8bd0
66f3ce8e975730f2dded8bd5
66f3ce8e975730f2dded8c35
66f3ce8e975730f2dded8c3e
66f3ce8e975730f2dded8c68
66f3ce8e975730f2dded8c88
66f3ce8e975730f2dded8c95
66f3ce8e975730f2dded8d98
66f3ce8e975730f2dded8db4
66f3ce8e975730f2dded8db5
66f3ce8e975730f2dded8db6
66f3ce8e975730f2dded8dc0
66f3ce8e975730f2dded8ddb
66f3ce8e975730f2dded8e4d
66f3ce8e975730f2dded8e5a
66f3ce8e975730f2dded8e63
66f3ce8e975730f2dded8e6b
66f3ce8e975730f2dded8ee0
66f3ce8e975730f2dded8ee2
66f3ce8e975730f2dded8ee3
66f3ce8e975730f2dded8ee4
66f3ce8e975730f2dded8f32
66f3ce8e975730f2dded8f63
66f3ce8e975730f2dded8f99
66f3ce8e975730f2dded902b
66f3ce8e975730f2dded9039
66f3ce8e975730f2dded903d
66f3ce8e975730f2dded9085
66f3ce8e975730f2dded9212
66f3ce8e975730f2dded935e
66f3ce8e975730f2dded94b4
66f3ce8e975730f2dded9515
66f3ce8e975730f2dded9564
66f3ce8e975730f2dded9571
66f3ce8e975730f2dded9572
66f3ce8e975730f2dded969d
66f3ce8e975730f2dded96b2
66f3ce8e975730f2dded96c2
66f3ce8e975730f2dded985a
66f3ce8e975730f2dded9895
66f3ce8e975730f2dded9906
66f3ce8e975730f2dded9a53
66f3ce8e975730f2dded9b5a
66f3ce8e975730f2dded9c49
66f3ce8e975730f2dded9f19
66f3ce8e975730f2dded9f61
66f3ce8e975730f2dded9fa3
66f3ce8e975730f2ddeda026
66f3ce8e975730f2ddeda308
66f3ce8e975730f2ddeda406
66f3ce8e975730f2ddeda445
66f3ce8e975730f2ddeda69c
66f3ce8e975730f2ddeda7a0
66f3ce8e975730f2ddedab26
66f3ce8e975730f2ddedab4c
66f3ce8e975730f2ddedab73
66f3ce8e975730f2ddedaca0
66f3ce8e975730f2ddedaeb5
66f3ce8e975730f2ddedaef4
66f3ce8e975730f2ddedaf06
66f3ce8e975730f2ddedb72b
66f3ce8e975730f2ddedc160
66f3ce8e975730f2ddedc439
66f3ce8e975730f2ddedc440
66f3ce8e975730f2ddedc4a7
66f3ce8e975730f2ddedc5a4
66f3ce8e975730f2ddedc674
66f3ce8e975730f2ddedce72
66f3ce8e975730f2ddedd2af
66f3ce8e975730f2ddedd37b
66f3ce8e975730f2ddedd3b9
66f3ce8e975730f2ddedd433
66f3ce8e975730f2ddedd56a
66f3ce8e975730f2ddedd5a8
66f3ce8e975730f2ddedd79e
66f3ce8e975730f2ddedd7aa
66f3ce8e975730f2ddedd7ac
66f3ce8e975730f2ddedd7ae
66f3ce8e975730f2ddedd7af
66f3ce8e975730f2ddedd7b0
66f3ce8e975730f2ddedd7b2
66f3ce8e975730f2ddedd7b3
66f3ce8e975730f2ddedd7b4
66f3ce8e975730f2ddedd7b5
66f3ce8e975730f2ddedd7b6
66f3ce8e975730f2ddedd7b7
66f3ce8e975730f2ddedd7b8
66f3ce8e975730f2ddedd7b9
66f3ce8e975730f2ddedd7bb
66f3ce8e975730f2ddedd7bc
66f3ce8e975730f2ddedd7bd
66f3ce8e975730f2ddedd7be
66f3ce8e975730f2ddedd7bf
66f3ce8e975730f2ddedd7c0
66f3ce8e975730f2ddedd7c1
66f3ce8e975730f2ddedd7c2
66f3ce8e975730f2ddedd7c3
66f3ce8e975730f2ddedd7c4
66f3ce8e975730f2ddedd7c5
66f3ce8e975730f2ddedd7c6
66f3ce8e975730f2ddedd7c7
66f3ce8e975730f2ddedd7c8
66f3ce8e975730f2ddedd7ff
66f3ce8e975730f2ddedd920
66f3ce8e975730f2ddedd952
66f3ce8e975730f2ddedd9a0
66f3ce8e975730f2ddeddb9e
66f3ce8e975730f2ddeddec4
66f3ce8e975730f2ddeddec9
66f3ce8e975730f2ddeddeca
66f3ce8e975730f2ddeddecb
66f3ce8e975730f2ddeddedb
66f3ce8e975730f2ddeddf92
66f3ce8e975730f2ddeddf9c
66f3ce8e975730f2ddeddf9e
66f3ce8e975730f2ddeddf9f
66f3ce8e975730f2ddeddfa0
66f3ce8e975730f2ddeddfa1
66f3ce8e975730f2ddeddfa2
66f3ce8e975730f2ddeddfa3
66f3ce8e975730f2ddeddfa4
66f3ce8e975730f2ddeddfa6
66f3ce8e975730f2ddeddfa7
66f3ce8e975730f2ddeddfa9
66f3ce8e975730f2ddeddfaa
66f3ce8e975730f2ddeddfab
66f3ce8e975730f2ddeddfac
66f3ce8e975730f2ddeddfad
66f3ce8e975730f2ddeddfae
66f3ce8e975730f2ddeddfb0
66f3ce8e975730f2ddeddfb1
66f3ce8e975730f2ddeddfb2
66f3ce8e975730f2ddeddfb4
66f3ce8e975730f2ddeddfb5
66f3ce8e975730f2ddede0f9
66f3ce8e975730f2ddede214
66f3ce8e975730f2ddede26e
66f3ce8e975730f2ddede31a
66f3ce8e975730f2ddede45e
66f3ce8e975730f2ddede46a
66f3ce8e975730f2ddede4d1
66f3ce8e975730f2ddedeada
66f3ce8e975730f2ddedee26
66f3ce8e975730f2ddedf0d9
66f3ce8e975730f2ddedf428
66f3ce8e975730f2ddedf48f
66f3ce8e975730f2ddedf80c
66f3ce8e975730f2ddedfcb4
66f3ce8e975730f2ddedfd77
66f3ce8e975730f2ddee01d8
66f3ce8e975730f2ddee028c
66f3ce8e975730f2ddee02ae
66f3ce8e975730f2ddee03ac
66f3ce8e975730f2ddee04d4
66f3ce8e975730f2ddee126b
66f3ce8e975730f2ddee12a6
66f3ce8e975730f2ddee12cc
66f3ce8e975730f2ddee139b
66f3ce8e975730f2ddee2275
66f3ce8e975730f2ddee2482
66f3ce8e975730f2ddee24ec
66f3ce8e975730f2ddee257f
66f3ce8e975730f2ddee2809
66f3ce8e975730f2ddee3756
66f3ce8e975730f2ddee3818
66f3ce8e975730f2ddee3f9b
66f3ce8e975730f2ddee465f
66f3ce8e975730f2ddee46b7
66f3ce8e975730f2ddee48e8
66f3ce8e975730f2ddee56ff
66f3ce8e975730f2ddee5708
66f3ce8e975730f2ddee579e
66f3ce8e975730f2ddee57b8
66f3ce8e975730f2ddee59cd
66f3ce8e975730f2ddee5cbb
66f3ce8e975730f2ddee5d6f
66f3ce8e975730f2ddee5e14
66f3ce8e975730f2ddee5e50
66f3ce8e975730f2ddee5e9a
66f3ce8e975730f2ddee5fc6
66f3ce8e975730f2ddee6029
66f3ce8e975730f2ddee641a
66f3ce8e975730f2ddee6425
66f3ce8e975730f2ddee6658
66f3ce8e975730f2ddee66fa
66f3ce8e975730f2ddee6d20
66f3ce8e975730f2ddee6d4b
66f3ce8e975730f2ddee6d7a
66f3ce8e975730f2ddee6ec6
66f3ce8e975730f2ddee70ea
66f3ce8e975730f2ddee79f0
66f3ce8e975730f2ddee7d61
66f3ce8e975730f2ddee800d
66f3ce8e975730f2ddee8a04
66f3ce8e975730f2ddee8c82
66f3ce8e975730f2ddee9119
66f3ce8e975730f2ddee92e8
66f3ce8e975730f2ddee9722
66f3ce8e975730f2ddee97dd
66f3ce8e975730f2ddee983a
66f3ce8e975730f2ddee9c04
66f3ce8e975730f2ddee9c2e
66f3ce8e975730f2ddee9c35
66f3ce8e975730f2ddee9d5a
66f3ce8e975730f2ddee9f7c
66f3ce8e975730f2ddeea1bf
66f3ce8e975730f2ddeea874
66f3ce8e975730f2ddeea9ba
66f3ce8e975730f2ddeead3c
66f3ce8e975730f2ddeeadcd
66f3ce8e975730f2ddeeae57
66f3ce8e975730f2ddeeb1b7
66f3ce8e975730f2ddeeb2c4
66f3ce8e975730f2ddeeb703
66f3ce8e975730f2ddeebafd
66f3ce8e975730f2ddeebd10
66f3ce8e975730f2ddeec46a
66f3ce8e975730f2ddeecb5f
66f3ce8e975730f2ddeecdcd
66f3ce8e975730f2ddeecdf2
66f3ce8e975730f2ddeed071
66f3ce8e975730f2ddeed6e3
66f3ce8e975730f2ddeee22a
66f3ce8e975730f2ddeeefe5
66f3ce8e975730f2ddeef605
66f3ce8e975730f2ddeefb4f
66f3ce8e975730f2ddeefcb8
66f3ce8e975730f2ddeefce1
66f3ce8e975730f2ddef0043
66f3ce8e975730f2ddef0046
66f3ce8e975730f2ddef0c79
66f3ce8e975730f2ddef136f
66f3ce8e975730f2ddef13db
66f3ce8e975730f2ddef1533
66f3ce8e975730f2ddef1547
66f3ce8e975730f2ddef190f
66f3ce8e975730f2ddef1c77
66f3ce8e975730f2ddef266b
66f3ce8e975730f2ddef26e5
66f3ce8e975730f2ddef3bbd
66f3ce8e975730f2ddef431d
66f3ce8e975730f2ddef45cf
66f3ce8e975730f2ddef5015
66f3ce8e975730f2ddef5552
66f3ce8e975730f2ddef56a9
66f3ce8e975730f2ddef58fa
66f3ce8e975730f2ddef5928
66f3ce8e975730f2ddef595e
66f3ce8e975730f2ddef5968
66f3ce8e975730f2ddef596a
66f3ce8e975730f2ddef5973
66f3ce8e975730f2ddef5d9c
66f3ce8e975730f2ddef62ec
66f3ce8e975730f2ddef64e0
66f3ce8e975730f2ddef671f
66f3ce8e975730f2ddef67e9
66f3ce8e975730f2ddef6bb6
66f3ce8e975730f2ddef6cd7
66f3ce8e975730f2ddef6fce
66f3ce8e975730f2ddef76c6
66f3ce8e975730f2ddef7a5b
66f3ce8e975730f2ddef8c13
66f3ce8e975730f2ddef8fca
66f3ce8e975730f2ddef99bf
66f3ce8f975730f2ddefa6e4
66f3ce8f975730f2ddefb26e
66f3ce8f975730f2ddefb646
66f3ce8f975730f2ddefb6b8
66f3ce8f975730f2ddefb916
66f3ce8f975730f2ddefbaf8
66f3ce8f975730f2ddefbd0f
66f3ce8f975730f2ddefbff5
66f3ce8f975730f2ddefbffd
66f3ce8f975730f2ddefc12f
66f3ce8f975730f2ddefc139
66f3ce8f975730f2ddefc53c
66f3ce8f975730f2ddefc738
66f3ce8f975730f2ddefcba8
66f3ce8f975730f2ddefcbe7
66f3ce8f975730f2ddefcf14
66f3ce8f975730f2ddefcf1c
66f3ce8f975730f2ddefd2af
66f3ce8f975730f2ddefd5bc
66f3ce8f975730f2ddefd833
66f3ce8f975730f2ddefd9ae
66f3ce8f975730f2ddefdd38
66f3ce8f975730f2ddefe035
66f3ce8f975730f2ddefe1f8
66f3ce8f975730f2ddefe370
66f3ce8f975730f2ddefe373
66f3ce8f975730f2ddefe58d
66f3ce8f975730f2ddefe69b
66f3ce8f975730f2ddefe785
66f3ce8f975730f2ddefe89c
66f3ce8f975730f2ddefe8ac
66f3ce8f975730f2ddefeae4
66f3ce8f975730f2ddefeca4
66f3ce8f975730f2ddeff177
66f3ce8f975730f2ddeff21b
66f3ce8f975730f2ddf002dd
66f3ce8f975730f2ddf0033f
66f3ce8f975730f2ddf00d2c
66f3ce8f975730f2ddf00e7f
66f3ce8f975730f2ddf01254
66f3ce8f975730f2ddf014ed
66f3ce8f975730f2ddf01f07
66f3ce8f975730f2ddf01f0a
66f3ce8f975730f2ddf036ad
66f3ce8f975730f2ddf03caf
66f3ce8f975730f2ddf047b2
66f3ce8f975730f2ddf04a25
66f3ce8f975730f2ddf04d3d
66f3ce8f975730f2ddf05824
66f3ce8f975730f2ddf05b1d
66f3ce8f975730f2ddf06792
66f3ce8f975730f2ddf06dc5
66f3ce8f975730f2ddf07026
66f3ce8f975730f2ddf070e7
66f3ce8f975730f2ddf074f1
66f3ce8f975730f2ddf075aa
66f3ce8f975730f2ddf078cf
66f3ce8f975730f2ddf07a2d
66f3ce8f975730f2ddf07a35
66f3ce8f975730f2ddf07a39
66f3ce8f975730f2ddf07b13
66f3ce8f975730f2ddf07b21
66f3ce8f975730f2ddf07ce4
66f3ce8f975730f2ddf08177
66f3ce8f975730f2ddf0828d
66f3ce8f975730f2ddf0831e
66f3ce8f975730f2ddf08873
66f3ce8f975730f2ddf08e43
66f3ce8f975730f2ddf09073
66f3ce8f975730f2ddf0942e
66f3ce8f975730f2ddf09437
66f3ce8f975730f2ddf09438
66f3ce8f975730f2ddf09439
66f3ce8f975730f2ddf09657
66f3ce8f975730f2ddf09752
66f3ce8f975730f2ddf099d1
66f3ce8f975730f2ddf09bb4
66f3ce8f975730f2ddf09eb9
66f3ce8f975730f2ddf09f88
66f3ce8f975730f2ddf09f95
66f3ce8f975730f2ddf0a174
66f3ce8f975730f2ddf0a17a
66f3ce8f975730f2ddf0a558
66f3ce8f975730f2ddf0ac9f
66f3ce8f975730f2ddf0ad03
66f3ce8f975730f2ddf0ae32
66f3ce8f975730f2ddf0ae5d
66f3ce8f975730f2ddf0b12a
66f3ce8f975730f2ddf0bc36
66f3ce8f975730f2ddf0bf22
66f3ce8f975730f2ddf0c10d
66f3ce8f975730f2ddf0c3f6
66f3ce8f975730f2ddf0c570
66f3ce8f975730f2ddf0c8e5
66f3ce8f975730f2ddf0cdbf
66f3ce8f975730f2ddf0d0fa
66f3ce8f975730f2ddf0d455
66f3ce8f975730f2ddf0dcac
66f3ce8f975730f2ddf0dff9
66f3ce8f975730f2ddf0e469
66f3ce8f975730f2ddf0e9ea
66f3ce8f975730f2ddf0eeec
66f3ce8f975730f2ddf0f128
66f3ce8f975730f2ddf0f217
66f3ce8f975730f2ddf0f324
66f3ce8f975730f2ddf0f679
66f3ce8f975730f2ddf0fb69
66f3ce8f975730f2ddf0fc15
66f3ce8f975730f2ddf0fc1e
66f3ce8f975730f2ddf10550
66f3ce8f975730f2ddf10759
66f3ce8f975730f2ddf10bff
66f3ce8f975730f2ddf10c05
66f3ce8f975730f2ddf10c06
66f3ce8f975730f2ddf10f40
66f3ce8f975730f2ddf111ac
66f3ce8f975730f2ddf113df
66f3ce8f975730f2ddf114e8
66f3ce8f975730f2ddf11624
66f3ce8f975730f2ddf11a66
66f3ce8f975730f2ddf12960
66f3ce8f975730f2ddf12e69
66f3ce8f975730f2ddf1375b
66f3ce8f975730f2ddf13fda
66f3ce8f975730f2ddf13fef
66f3ce8f975730f2ddf147b7
66f3ce8f975730f2ddf14ac3
66f3ce8f975730f2ddf14dde
66f3ce8f975730f2ddf14f61
66f3ce8f975730f2ddf16ada
66f3ce8f975730f2ddf17522
66f3ce8f975730f2ddf17666
66f3ce8f975730f2ddf176b8
66f3ce8f975730f2ddf17979
66f3ce8f975730f2ddf17a05
66f3ce8f975730f2ddf17a6e
66f3ce8f975730f2ddf17c2a
66f3ce8f975730f2ddf17cbe
66f3ce8f975730f2ddf17d70
66f3ce8f975730f2ddf182d5
66f3ce8f975730f2ddf1874b
66f3ce8f975730f2ddf188a4
66f3ce8f975730f2ddf18aad
66f3ce8f975730f2ddf18cf0
66f3ce8f975730f2ddf18ebb
66f3ce8f975730f2ddf1908c
66f3ce8f975730f2ddf192ba
66f3ce8f975730f2ddf197a8
66f3ce8f975730f2ddf197b1
66f3ce8f975730f2ddf197cc
66f3ce8f975730f2ddf197d2
66f3ce8f975730f2ddf1993b
66f3ce8f975730f2ddf19b06
66f3ce8f975730f2ddf19b8d
66f3ce8f975730f2ddf19c01
66f3ce8f975730f2ddf19e6a
66f3ce8f975730f2ddf19eef
66f3ce8f975730f2ddf1a14e
66f3ce8f975730f2ddf1a454
66f3ce8f975730f2ddf1ad94
66f3ce8f975730f2ddf1ad9f
66f3ce8f975730f2ddf1ae20
66f3ce8f975730f2ddf1af23
66f3ce8f975730f2ddf1af9a
66f3ce8f975730f2ddf1b091
66f3ce8f975730f2ddf1b3b3
66f3ce8f975730f2ddf1b456
66f3ce8f975730f2ddf1b4ba
66f3ce8f975730f2ddf1b5df
66f3ce8f975730f2ddf1b5ef
66f3ce8f975730f2ddf1b7bb
66f3ce8f975730f2ddf1b83c
66f3ce8f975730f2ddf1b9ae
66f3ce8f975730f2ddf1baa9
66f3ce8f975730f2ddf1c07a
66f3ce8f975730f2ddf1c0b0
66f3ce8f975730f2ddf1c577
66f3ce8f975730f2ddf1c60a
66f3ce8f975730f2ddf1c64e
66f3ce8f975730f2ddf1cc8a
66f3ce8f975730f2ddf1cfca
66f3ce8f975730f2ddf1d912
66f3ce8f975730f2ddf1d913
66f3ce8f975730f2ddf1d914
66f3ce8f975730f2ddf1d915
66f3ce8f975730f2ddf1d9b4
66f3ce8f975730f2ddf1dc51
66f3ce8f975730f2ddf1df9e
66f3ce8f975730f2ddf1e019
66f3ce8f975730f2ddf1e5f6
66f3ce8f975730f2ddf1e795
66f3ce8f975730f2ddf1eaf2
66f3ce8f975730f2ddf1ef73
66f3ce8f975730f2ddf1efa2
66f3ce8f975730f2ddf1f24f
66f3ce8f975730f2ddf1f262
66f3ce8f975730f2ddf1f2bc
66f3ce8f975730f2ddf1f575
66f3ce8f975730f2ddf1f7b7
66f3ce8f975730f2ddf1fdec
66f3ce8f975730f2ddf2097c
66f3ce8f975730f2ddf20b41
66f3ce8f975730f2ddf20e8e
66f3ce8f975730f2ddf217bd
66f3ce8f975730f2ddf21943
66f3ce8f975730f2ddf21a49
66f3ce8f975730f2ddf21ad5
66f3ce8f975730f2ddf21ad6
66f3ce8f975730f2ddf21eda
66f3ce8f975730f2ddf22d97
66f3ce8f975730f2ddf22e26
66f3ce8f975730f2ddf230d2
66f3ce8f975730f2ddf2351d
66f3ce8f975730f2ddf236d7
66f3ce8f975730f2ddf238e0
66f3ce8f975730f2ddf23b8a
66f3ce8f975730f2ddf23e7f
66f3ce8f975730f2ddf23f74
66f3ce8f975730f2ddf23f97
66f3ce8f975730f2ddf24953
66f3ce8f975730f2ddf24b59
66f3ce8f975730f2ddf25ecd
66f3ce8f975730f2ddf263e6
66f3ce8f975730f2ddf263f3
66f3ce8f975730f2ddf2680d
66f3ce8f975730f2ddf270eb
66f3ce8f975730f2ddf27871
66f3ce8f975730f2ddf27ab9
66f3ce8f975730f2ddf27b04
66f3ce8f975730f2ddf27e33
66f3ce8f975730f2ddf27ebb
66f3ce8f975730f2ddf28126
66f3ce8f975730f2ddf282bf
66f3ce8f975730f2ddf2839f
66f3ce8f975730f2ddf284d4
66f3ce8f975730f2ddf284fd
66f3ce8f975730f2ddf28642
66f3ce8f975730f2ddf286cd
66f3ce8f975730f2ddf28748
66f3ce8f975730f2ddf28ca6
66f3ce8f975730f2ddf2934a
66f3ce8f975730f2ddf2962e
66f3ce8f975730f2ddf29738
66f3ce8f975730f2ddf29841
66f3ce8f975730f2ddf2999b
66f3ce8f975730f2ddf299c9
66f3ce8f975730f2ddf29bdd
66f3ce8f975730f2ddf29d24
66f3ce8f975730f2ddf29d51
66f3ce8f975730f2ddf2a053
66f3ce8f975730f2ddf2a1dc
66f3ce8f975730f2ddf2a8f8
66f3ce8f975730f2ddf2b3b1
66f3ce8f975730f2ddf2c0ad
66f3ce8f975730f2ddf2c9da
66f3ce8f975730f2ddf2d40d
66f3ce8f975730f2ddf2d920
66f3ce8f975730f2ddf2dc4e
66f3ce8f975730f2ddf2dd30
66f3ce8f975730f2ddf2dd84
66f3ce8f975730f2ddf2df62
66f3ce8f975730f2ddf2e43a
66f3ce8f975730f2ddf2e47f
66f3ce8f975730f2ddf2e921
66f3ce8f975730f2ddf2f0ae
66f3ce8f975730f2ddf2f0f0
66f3ce8f975730f2ddf2ff3a
66f3ce8f975730f2ddf300b7
66f3ce8f975730f2ddf300b8
66f3ce8f975730f2ddf300ba
66f3ce8f975730f2ddf300bc
66f3ce8f975730f2ddf300be
66f3ce8f975730f2ddf300c0
66f3ce8f975730f2ddf300c1
66f3ce8f975730f2ddf300c2
66f3ce8f975730f2ddf300c4
66f3ce8f975730f2ddf300c6
66f3ce8f975730f2ddf300c9
66f3ce8f975730f2ddf300ca
66f3ce8f975730f2ddf300cb
66f3ce8f975730f2ddf300cc
66f3ce8f975730f2ddf3013a
66f3ce8f975730f2ddf303fa
66f3ce8f975730f2ddf3059b
66f3ce8f975730f2ddf306a4
66f3ce8f975730f2ddf30a49
66f3ce8f975730f2ddf30c00
66f3ce8f975730f2ddf30ea9
66f3ce8f975730f2ddf30eaa
66f3ce8f975730f2ddf30eac
66f3ce8f975730f2ddf30ead
66f3ce8f975730f2ddf30ee8
66f3ce8f975730f2ddf3116d
66f3ce8f975730f2ddf314e5
66f3ce8f975730f2ddf32260
66f3ce8f975730f2ddf32345
66f3ce8f975730f2ddf32355
66f3ce8f975730f2ddf32698
66f3ce8f975730f2ddf327eb
66f3ce8f975730f2ddf32839
66f3ce8f975730f2ddf32974
66f3ce8f975730f2ddf32d24
66f3ce8f975730f2ddf33230
66f3ce8f975730f2ddf332e4

In [29]:
db.cell.update_many({}, {"$set": {"type": "code"}})

In [6]:
from nb2p.dataset import materialize


materialize(db)